/*
 *  Copyright 2009 Roman Naumann <roman_naumann@fastmail.fm>.
 *
 *  This file is part of DDD.
 *
 *  DDD is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with DDD.  If not, see <http://www.gnu.org/licenses/>.
 */

/*
 * SchadenGui.java
 *
 * Created on 30.05.2009, 19:39:09
 */
package gui;

import ddd.Wuerfel;

/**
 *
 * @author namor
 */
public class SchadenGui extends javax.swing.JFrame {

    /** Creates new form SchadenGui */
    public SchadenGui() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        _b_schaden = new javax.swing.JButton();
        _verteidigung = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        _staerkebonus_prozent = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        _waffenstaerke = new javax.swing.JTextField();
        _trefferwucht = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        _trefferzone = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        _b_attacke = new javax.swing.JButton();
        _mod_abs = new javax.swing.JTextField();
        _mod_prozent = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        _probenwert = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        _angriffsergebnis = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        _trefferqualitaet = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Schaden!");

        _b_schaden.setForeground(new java.awt.Color(255, 0, 0));
        _b_schaden.setText("Schaden!");
        _b_schaden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _b_schadenActionPerformed(evt);
            }
        });

        _verteidigung.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "EXZELLENT", "MEISTERLICH", "GUT", "GELUNGEN", "SCHLECHT", "MISSLUNGEN", "LEICHTER_PATZER", "MITTLERER_PATZER", "SCHWERER_PATZER", " " }));
        _verteidigung.setSelectedIndex(3);
        _verteidigung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _verteidigungActionPerformed(evt);
            }
        });

        jLabel1.setText("Verteidigung:");

        jLabel2.setText("Angriff:");

        jLabel3.setText("Trefferwucht:");

        _staerkebonus_prozent.setText("0");

        jLabel4.setText("Trefferzone");

        jLabel5.setText("Waffenstärke:");

        _waffenstaerke.setText("10");

        _trefferwucht.setForeground(new java.awt.Color(255, 0, 0));

        jLabel6.setText("Stärkebonus %:");

        _trefferzone.setForeground(new java.awt.Color(255, 0, 0));

        jLabel7.setText("Ergebnis:");

        _b_attacke.setForeground(new java.awt.Color(0, 255, 0));
        _b_attacke.setText("Angriff!");
        _b_attacke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _b_attackeActionPerformed(evt);
            }
        });

        _mod_abs.setText("00");
        _mod_abs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                _mod_absActionPerformed(evt);
            }
        });

        _mod_prozent.setText("00");

        jLabel8.setText("Modifikator Prozent:");

        _probenwert.setText("30");

        jLabel9.setText("Probenwert-Angriff:");

        jLabel10.setText("Modifikator Absolut:");

        _angriffsergebnis.setForeground(new java.awt.Color(0, 255, 0));

        jLabel11.setText("Trefferqualität:");

        _trefferqualitaet.setForeground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(_verteidigung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(_staerkebonus_prozent)
                            .addComponent(_waffenstaerke))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(_trefferqualitaet, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(19, 19, 19)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(_trefferzone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(_trefferwucht, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_mod_prozent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_mod_abs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(_probenwert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(_b_attacke)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(_b_schaden))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(_angriffsergebnis, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(_probenwert, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(_mod_abs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(_mod_prozent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(_angriffsergebnis, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(_trefferqualitaet, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(_trefferwucht, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(_trefferzone, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(_staerkebonus_prozent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(_waffenstaerke, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(_verteidigung, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(_b_schaden)
                    .addComponent(_b_attacke))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void _verteidigungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__verteidigungActionPerformed
        try{
            aktualisiereVerhaeltnis();
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event__verteidigungActionPerformed

    private void _mod_absActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__mod_absActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event__mod_absActionPerformed

    private void _b_attackeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__b_attackeActionPerformed
        try {
            int PWbasis = Integer.parseInt(_probenwert.getText());

            int mod_abs = Integer.parseInt(_mod_abs.getText());
            int mod_pro = Integer.parseInt(_mod_prozent.getText());

            int PWfinal = PWbasis + mod_abs + PWbasis * mod_pro / 100;

            if (PWfinal < 5) {
                PWfinal = 5;
            }
            if (PWfinal > 90) {
                PWfinal = 90;
            }

            _angriffsergebnis.setText("" + Wuerfel.probe(PWfinal));

            aktualisiereVerhaeltnis();

        } catch (Exception e) {
            e.printStackTrace();
            System.exit(1);
        }
}//GEN-LAST:event__b_attackeActionPerformed

    public void aktualisiereVerhaeltnis() throws Exception{
        Wuerfel.PROBENQUALITAET angriff = Wuerfel.PROBENQUALITAET.valueOf(_angriffsergebnis.getText());
        Wuerfel.PROBENQUALITAET verteidigung = Wuerfel.PROBENQUALITAET.valueOf((String) _verteidigung.getSelectedItem());
        _trefferqualitaet.setText("" + Wuerfel.trefferqualitaet(angriff, verteidigung));

    }

    private void _b_schadenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event__b_schadenActionPerformed
        try {
            int waffenstaerke = Integer.parseInt(_waffenstaerke.getText());
            double staerkebonus_fac = 0.01 * Integer.parseInt(
                    _staerkebonus_prozent.getText());

            _trefferwucht.setText("" + (Wuerfel.waffenWucht(waffenstaerke) +
                    (int) (staerkebonus_fac * waffenstaerke)));
            _trefferzone.setText("" + Wuerfel.trefferzone());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event__b_schadenActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new SchadenGui().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel _angriffsergebnis;
    private javax.swing.JButton _b_attacke;
    private javax.swing.JButton _b_schaden;
    private javax.swing.JTextField _mod_abs;
    private javax.swing.JTextField _mod_prozent;
    private javax.swing.JTextField _probenwert;
    private javax.swing.JTextField _staerkebonus_prozent;
    private javax.swing.JLabel _trefferqualitaet;
    private javax.swing.JLabel _trefferwucht;
    private javax.swing.JLabel _trefferzone;
    private javax.swing.JComboBox _verteidigung;
    private javax.swing.JTextField _waffenstaerke;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
